export const ACTION_TYPES = {
    LOADING_BLOCKS: 'LOADING_BLOCKS',
    LOADING_BLOCKS_SUCCESS: 'LOADING_BLOCKS_SUCCESS',
    LOADING_BLOCKS_ERROR: 'LOADING_BLOCKS_ERROR',
    SET_BLOCKS_LIMIT: 'SET_BLOCKS_LIMIT',
    SET_BLOCKS_START: 'SET_BLOCKS_START',
    LOADING_BLOCK: 'LOADING_BLOCK',
    LOADING_BLOCK_SUCCESS: 'LOADING_BLOCK_SUCCESS',
    LOADING_BLOCK_ERROR: 'LOADING_BLOCK_ERROR'
};